### PR TITLE
First pass at doc update for kim type labels

### PR DESCRIPTION
**Pull request by ilia-nikiforov-umn**
Covers the basic functionality of the new SMs

### CODE REVIEW

**Comment by yafshar** [comment]
@ilia-nikiforov-umn, thanks, this is a good start, but it is incomplete. This doc is missing a new command, `kim create box,` and I think it needs an example (or maybe discussion) for creating a new bonded system using kim commands.

**Comment by ilia-nikiforov-umn** [comment]
> @ilia-nikiforov-umn, thanks, this is a good start, but it is incomplete. This doc is missing a new command, `kim create box,` and I think it needs an example (or maybe discussion) for creating a new bonded system using kim commands.

Do you think an example "how to make core/shell simulations using KIM" is sufficient, or do you think a more elaborate example involving angles, dihedrals, and impropers is necessary?

**Comment by yafshar** [comment]
> > @ilia-nikiforov-umn, thanks, this is a good start, but it is incomplete. This doc is missing a new command, `kim create box,` and I think it needs an example (or maybe discussion) for creating a new bonded system using kim commands.
> 
> Do you think an example "how to make core/shell simulations using KIM" is sufficient, or do you think a more elaborate example involving angles, dihedrals, and impropers is necessary?

Both are necessary. Thanks

**Comment by yafshar** [comment]
@ilia-nikiforov-umn, I have updated the branch with the latest develop branch. Can you please create a new PR with only your changes

**Pull request closed without merging**
